# Generated by Django 5.1.3 on 2024-11-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_fio', models.CharField(max_length=255)),
                ('parent_phone', models.CharField(max_length=20)),
                ('child_fio', models.CharField(max_length=255)),
                ('child_dob', models.DateField()),
            ],
        ),
    ]
