# Generated by Django 5.1.3 on 2024-11-21 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avalon', '0002_record_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='child_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='child_fio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
